### ISSUE TITLE
installed_apps.py not found

### ISSUE THREAD

**Issue by HNaga** [falconsoft3d/pyerp#8]
when running python manage.py init_pyerp
I got thefollowing error 
File "E:\Dev\Django\pyerp-master\pyerp\settings.py", line 80, in <module>
    with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Dev\\Django\\pyerp-master/installed_apps.py'

**Comment by Alvezgr** [comment]
Hi @HNaga you solve the problem already? I have the same issue. I thing might creating the file in the root folder will solve.

**Comment by bascolgar** [comment]
Hola Marlon, me ocurre el mismo problema estoy siguiendo sus videos en youtube y al tratar de instalar los fuentes del ERP no encuentra el fichero  installed_apps.py adjunto traza completa saludos.

2020-05-20 14:59:47,208 - DEBUG -settings.py:24 - hello world!
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/basilio/.virtualenvs/WebManager/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/basilio/.virtualenvs/WebManager/lib/python3.8/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/basilio/.virtualenvs/WebManager/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/basilio/.virtualenvs/WebManager/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/basilio/.virtualenvs/WebManager/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/basilio/proyectos/pyerp-master/pyerp/settings.py", line 80, in <module>
    with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/basilio/proyectos/pyerp-master/installed_apps.py'

**Comment by thiago000** [comment]
brother was having the same problem
I took the requirements.txt file and moved it into the pyerp folder
then just follow the steps:
cd pyerp
pip3 install -r requirements.txt
python manage.py init_pyerp
python manage.py runserver

**Comment by gridworkz** [comment]
Same issue here. 

2020-08-18 10:49:04,692 - DEBUG -settings.py:24 - hello world!
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/osboxes/gridworkz/pyerp/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/osboxes/gridworkz/pyerp/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/osboxes/gridworkz/pyerp/env/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/osboxes/gridworkz/pyerp/env/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/osboxes/gridworkz/pyerp/env/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/osboxes/gridworkz/pyerp/pyerp/settings.py", line 80, in <module>
    with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/osboxes/gridworkz/pyerp/installed_apps.py'

UPDATE: Just created an empty installed_apps.py file and we're good now. Read the other thread on this.

**Comment by ddiaz2380** [comment]
Just creating installed_apps.py solves it? Because I did, I was able to run the project, but when I wanted to migrate the base, I only migrated the django structure without the other tables.

**Comment by gridworkz** [comment]
Thanks, I'll give that a try.

**Comment by youssriaboelseod** [comment]
i create pull request for adding installed_app.py

**Comment by gridworkz** [comment]
Thanks, yep that didi it.
Cheers,
Dave

**Comment by ddiaz2380** [comment]
Could you run the application? I can't, I want to migrate the tables and it doesn't give me an error.

**Comment by gridworkz** [comment]
Yes, it runs fine now after creating the installed_apps.py file. Cheers,
Dave

**Comment by MirvohidovM** [comment]
same error, because  installed _apps written in .gitignore,  how to solve that?

**Comment by BrenoOsvaldoFunicheli** [comment]
You can solve this problem by creating the installed _apps.py and after running the python manage.py init_pyerp.

Because the app need the file created, so after this it will be fill the file. 
If you in run in the linux you can be.

touch installed _apps.py
python manage.py init_pyerp
